export const ResponseMessage = {
  email_already_associate_with_another_account:
    'Email already associated with another account',
  You_dont_have_permission_to: "You don't have permission to",
  something_Went_Wrong: 'Something Went Wrong',
  business_email_is_already_registered: 'Business email is already registered',
  mobile_number_is_already_registered: 'Mobile number is already registered',
  this_mobile_number_is_already_registered_please_add_another_mobile_number:
    'This mobile number is already registered, please add another mobile number',
  successfully_operation: 'Successfully operation',
  something_went_wrong: 'Something went wrong',
  internal_server_error: 'Internal server error',
  message: 'Message',
  error_message: 'Error message',
  data_not_found: 'Data not found',
  success: 'Success',
  image_added_successfully: 'Image added successfully',
  email_verification_successfully: 'Email verification successfully',
  please_enter_valid_otp: 'Please enter valid otp',
  otp_sent_successfully: 'Otp sent successfully',
  otp_sending_failed: 'Otp sending failed',
  please_enter_valid_email_or_mobile_number:
    'Please enter a valid email or mobile number',
  please_enter_valid_mobile_number: 'Please enter a mobile number',
  otp_verify_successfully: 'otp verify successfully',
  otp_verify_fail: 'Otp verify fail',
  invalid_number_or_otp: 'Invalid number or otp',
  invalid_email: 'Invalid email',
  login_successful: 'Login successfully',
  user_login_data_successful: 'User login data successfully',
  login_fail: 'Login fail',
  logout_successfully: 'Logout successfully',
  logout_failed: 'Logout failed',
  business_owner_not_found: 'Business owner not found',
  email_sent: 'Email sent',
  email_sent_fail: 'Email sent fail',
  category_already_exists: 'Category already exists',
  category_added_successfully: 'Category added successfully',
  category_update_successfully: 'Category update successfully',
  category_updating_fail: 'Category updating fail',
  category_not_found: 'Category not found',
  category_delete_successfully: 'Category delete successfully',
  category_delete_fail: 'Category delete fail',
  invalid_category_id: 'Invalid category id',
  invalid_id: 'Invalid id',
  name_is_required: 'Please enter your name',
  name_already_exists: 'Name already exists',
  business_type_added_successfully: 'Business type added successfully',
  get_all_business_type_data_successfully:
    'Get All Business Type Data Successfully',
  get_by_id_business_type_data_successfully:
    'Get By Id Business Type Data Successfully',
  business_type_updated_successfully: 'Business type updated successfully',
  business_type_deleted_successfully: 'Business type deleted successfully',
  please_try_to_correct_credentials: 'Please try to correct credentials',
  successfully_deleted_the_file: 'Successfully deleted the file.',
  please_enter_contact_number: 'Please enter contact number.',
  update_fail: 'Update fail.',
  update_successfully: 'Update successfully.',
  delete_successfully: 'Delete successfully.',
  contact_number_required: 'Contact number required.',
  staff_added_successfully: 'Staff added successfully',
  get_staff_successfully: 'Get staff successfully',
  get_bt_id_staff_successfully: 'Get By Id staff successfully',
  staff_not_found: 'Staff not found',
  unit_name_already_exists: 'Unit name already exists',
  unit_added_successfully: 'Unit added successfully',
  get_unit_successfully: 'Get Unit successfully',
  unit_updated_successfully: 'Unit updated successfully',
  unit_deleted_successfully: 'Unit deleted successfully',
  tax_name_already_exists: 'Tax name already exists',
  tax_added_successfully: 'Tax added successfully',
  get_tax_successfully: 'Get tax successfully',
  tax_updated_successfully: 'Tax updated successfully',
  tax_deleted_successfully: 'Tax Deleted successfully',
};
